name: Windows Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements_dev.txt'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install generic requirements
        run: python -m pip install -r requirements_dev.txt
      - name: Install Windows requirements
        run: python -m pip install pywin32
      - name: Build package
        run: python setup.py build
      - name: Install package
        run: python setup.py install
      - name: Run Unit tests
        run: pytest
