name: Windows Unit Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements_dev.txt'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: python -m pip install -r requirements_dev.txt
      - name: Build package
        run: python setup.py build
      - name: Install package
        run: python setup.py install
      - name: Run Unit tests
        run: pytest
